title:              日常学习记录
email:              yzy520418@gmail.com
description:        主要用来记录做运维的学习过程
author:             ZhaoYu Yang
baseurl:            "/"
url:                "https://blog.moros.vip"

# Social Profiles
twitter_username:   ZhaoYu Yang
github_username:    AdrestiaOS
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-H7YE4S65WM # out your google-analytics code

# Build settings
markdown:           kramdown
kramdown:
  input: GFM
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
